version: "3.5"

services:
  postgresql:
    image: postgres
    container_name: goku-postgresql
    restart: always
    environment:
      - POSTGRES_USER=goku_adm
      - POSTGRES_PASSWORD=goku_adm
      - POSTGRES_DB=goku_adm
      - PGDATA=/tmp
    ports:
      - 25432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-volume/postgres-data:/var/lib/postgresql/data
      - ./postgres-volume/postgres-data-tablespace:/var/lib/postgresql/data/tablespace
      - ./postgres-volume/postgresql-scripts:/var/lib/postgresql/scripts
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@goku.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 15432:80
    networks:
      - postgres-network

  memcached:
    image: 'docker.io/bitnami/memcached:1-debian-10'
    ports:
      - '11211:11211'

networks:
  postgres-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24